const wordList=[
        { word: "apple", hint: "A type of fruit with a smooth skin that can be red, green, or yellow, often associated with health." },
        { word: "zebra", hint: "A herbivore known for its distinctive black and white pattern, usually found in savannahs." },
        { word: "python", hint: "A general-purpose, high-level language that is popular for data science and artificial intelligence." },
        { word: "ocean", hint: "A vast, saline water body that covers a significant part of the Earth's surface and is home to diverse marine life." },
        { word: "basket", hint: "A lightweight, often cylindrical container traditionally woven from natural materials." },
        { word: "chocolate", hint: "A confection made from ground beans, often sweetened, and used in a variety of desserts." },
        { word: "triangle", hint: "A polygon with the minimum number of edges that can exist in Euclidean geometry." },
        { word: "volcano", hint: "A geological feature that expels molten rock, ash, and gases from beneath the Earth's surface." },
        { word: "nebula", hint: "An astronomical phenomenon characterized by a diffuse cloud of dust and gas, often a star-forming region." },
        { word: "dragonfly", hint: "An insect known for its agility in flight, large compound eyes, and predatory behavior during its adult stage." },
        { word: "guitar", hint: "A stringed instrument often used in both acoustic and electric forms, producing sound through vibration." },
        { word: "galaxy", hint: "A gravitationally bound system that consists of stars, stellar remnants, and dark matter, typically in a spiral or elliptical shape." },
        { word: "rainbow", hint: "An optical phenomenon caused by refraction, reflection, and dispersion of light in water droplets, resulting in a multicolored arc." },
        { word: "pyramid", hint: "An ancient, monumental structure with a square or triangular base that tapers to a point, often used as a royal tomb." },
        { word: "engineer", hint: "A professional involved in the application of scientific and mathematical principles to develop solutions in various industries." },
        { word: "mountain", hint: "A large landform that rises prominently above its surroundings, formed by tectonic forces or volcanism." },
        { word: "archaeology", hint: "The study of human activity through the recovery and analysis of material culture from the past." },
        { word: "quarantine", hint: "A state of enforced isolation, typically to prevent the spread of contagious diseases or conditions." },
        { word: "dolphin", hint: "An aquatic mammal known for its intelligence and social behavior, often found in oceans and rivers." },
        { word: "satellite", hint: "An artificial or natural object placed into orbit around a larger celestial body, often used for communication or observation." },
        { word: "revolution", hint: "A significant change in political power or organizational structures that occurs in a short period, often accompanied by social upheaval." },
        { word: "bioluminescence", hint: "The emission of light by living organisms as a result of chemical reactions, typically found in marine species." },
        { word: "philosophy", hint: "The academic study of fundamental questions concerning existence, knowledge, and values." },
        { word: "volleyball", hint: "A team sport where players aim to score points by hitting a ball over a net into the opponent’s court." },
        { word: "microscope", hint: "An instrument used to observe objects that are too small to be seen by the naked eye, often employed in biological research." },
        { word: "oxygen", hint: "A reactive gas that is vital for respiration in most living organisms and is a major component of the Earth's atmosphere." },
        { word: "crocodile", hint: "A large, predatory reptile, often found in tropical regions near freshwater habitats." },
        { word: "telescope", hint: "An optical device designed to observe distant objects, particularly celestial bodies like stars and planets." },
        { word: "magnetism", hint: "A physical property resulting from the movement of charged particles, producing attraction or repulsion between objects." },
        { word: "ecosystem", hint: "A community of interacting organisms and their physical environment, functioning as a unit." },
        { word: "universe", hint: "The totality of space, time, matter, and energy, including all galaxies, stars, planets, and other celestial bodies." },
        { word: "molecule", hint: "The smallest particle of a chemical element or compound, made up of atoms bonded together." },
        { word: "jellyfish", hint: "A gelatinous marine animal with tentacles, known for drifting in oceans and occasionally stinging swimmers." },
        { word: "hurricane", hint: "A massive storm system characterized by strong winds and heavy rain, typically originating over warm tropical waters." },
        { word: "xylophone", hint: "A percussion instrument with wooden bars that are struck to produce sound, often arranged in a scale." },
        { word: "kangaroo", hint: "A marsupial native to Australia, known for its large hind legs and hopping locomotion." },
        { word: "helicopter", hint: "A rotary-wing aircraft capable of vertical takeoff, hovering, and landing, often used for rescue or transport." },
        { word: "electricity", hint: "A form of energy resulting from the movement of charged particles, powering most modern technology." },
        { word: "optometry", hint: "The field of healthcare concerned with the eyes and related visual systems, including vision correction." },
        { word: "tornado", hint: "A destructive atmospheric phenomenon involving a rotating column of air extending from a thunderstorm to the ground." },
        { word: "astronomy", hint: "The scientific study of celestial objects, space, and the universe as a whole." },
        { word: "avalanche", hint: "A rapid flow of snow down a slope, often triggered by changes in weather or physical disturbance." },
        { word: "camouflage", hint: "A natural adaptation or artificial method used to conceal individuals or objects from detection." },
        { word: "chemistry", hint: "The scientific study of substances, their properties, interactions, and the reactions that change them into other substances." },
        { word: "skyscraper", hint: "A very tall, continuously habitable building with multiple floors, typically found in urban areas." },
        { word: "scorpion", hint: "An arachnid known for its venomous stinger and predatory behavior, found in warm climates." },
        { word: "espresso", hint: "A concentrated form of coffee brewed by forcing hot water under pressure through finely ground coffee beans." },
        { word: "saturn", hint: "A gas giant planet in our solar system, notable for its extensive ring system." },
        { word: "avocado", hint: "A green-skinned fruit with a single large seed, commonly used in salads and dips." },
        { word: "octopus", hint: "A soft-bodied marine animal with eight arms, known for its intelligence and ability to camouflage." },
        { word: "parachute", hint: "A device used to slow descent through the atmosphere, typically deployed in skydiving or emergency situations." },
        { word: "whirlpool", hint: "A rapidly rotating body of water that forms a vortex, often found near waterfalls or in ocean currents." },
        { word: "waterfall", hint: "A natural feature where water flows over a vertical drop, often forming a plunge pool below." },
        { word: "iridescent", hint: "Displaying a spectrum of colors that shimmer and change depending on the angle of light." },
        { word: "chameleon", hint: "A reptile known for its ability to change color and for its long, sticky tongue used to capture prey." },
        { word: "bicycle", hint: "A human-powered vehicle with two wheels, a frame, and pedals, commonly used for transportation and exercise." },
        { word: "parallelogram", hint: "A quadrilateral with opposite sides that are both equal and parallel, but without right angles." },
        { word: "tundra", hint: "A cold, treeless biome found in polar regions, characterized by a short growing season and permafrost." },
        { word: "crystal", hint: "A solid material whose atoms are arranged in a highly ordered, repeating pattern extending in all directions." },
        { word: "whisper", hint: "To speak softly and without vocal cord vibration, often to avoid being overheard." },
        { word: "equator", hint: "An imaginary line dividing the Earth into northern and southern hemispheres, located at 0 degrees latitude." },
        { word: "caterpillar", hint: "The larval stage of a butterfly or moth, often seen feeding on leaves before metamorphosis." },
        { word: "meadow", hint: "A grassland habitat filled with wildflowers and herbs, often found in temperate climates." },
        { word: "climate", hint: "The long-term pattern of weather conditions in a specific region." },
        { word: "labyrinth", hint: "A complex network of paths or passages that are difficult to navigate, often associated with ancient myths." },
        { word: "symphony", hint: "A large-scale musical composition, typically for an orchestra, structured in multiple movements." },
        { word: "hologram", hint: "A three-dimensional image created using light interference, often projected or displayed on a surface." },
        { word: "hippopotamus", hint: "A large, semi-aquatic mammal native to sub-Saharan Africa, known for its massive size and aggressive"}     
]